### ISSUE TITLE
(Documentation) Interval parameter is incorrectly shown

### ISSUE THREAD

**Issue by calvinl** [zackurben/alphavantage#38]
In the docs, it shows this for an intraday request with an interval:

```
alpha.data.intraday(symbol, interval)
```

However, the following doesn't work (interval is still set to 1min):
```
alpha.data.intraday(symbol, '5min')
```

This does, however:
```
alpha.data.intraday(symbol, 'compact', 'json', '5min');
```

Perhaps a config object would make more sense here, and/or updating the docs to be clearer about this?

Also, thanks for this great library!

**Comment by zackurben** [comment]
Hey @calvinl, great catch! This looks like a copy/paste fail; I'll get those docs updated asap. As a temporary reference for you and others, the real signature is:

`alpha.data.intraday(symbol, <output size>, <datatype>, <interval>);`

Where the `< .. >` params are optional.

I wont rule out a config option now, but I rather postpone that talk for now, due to the refactor required. Thanks for the feedback - Cheers!

**Comment by zackurben** [comment]
@calvinl I'd also be willing to accept a pr if you want to make one! The signature is the same for [all the data functions](https://github.com/zackurben/alphavantage/blob/master/lib/data.js#L26-L32) besides `batch`.

**Comment by calvinl** [comment]
@zackurben thanks for confirming that! I'll see if I can take a stab at that this weekend. :)
