### ISSUE TITLE
Looking for way to interface this with a vue/nuxtjs app

### ISSUE THREAD

**Issue by rlam3** [zackurben/alphavantage#64]
Looking for way to interface this with a vue/nuxtjs app.

I keep hitting this problem where I'm not able to import alphavantage through plugins... Was wondering if there was something wrong with package.json? Thanks! 

```
ERROR in ./node_modules/alphavantage/node_modules/dotenv/lib/main.js
Module not found: Error: Can't resolve 'fs' in '/Users/XXXXX/Projects/myApp/myApp/node_modules/alphavantage/node_modules/dotenv/lib'
ERROR in ./node_modules/request/lib/har.js
Module not found: Error: Can't resolve 'fs' in '/Users/XXXXX/Projects/myApp/myApp/node_modules/request/lib'
```

```vue
/** plugins/alphavantage.js
 * Init Alpha Vantage with your API key.
 *
 * @param {String} key
 *   Your Alpha Vantage API key.
 */
import AlphaVantage from 'alphavantage'
import Vue from 'vue'
const alpha = AlphaVantage({
  key: '0ZC3SK0K7V1R4UZZ'
})

Vue.use(alpha)

```

**Comment by MujahidAbbas** [comment]
> Looking for way to interface this with a vue/nuxtjs app.
> 
> I keep hitting this problem where I'm not able to import alphavantage through plugins... Was wondering if there was something wrong with package.json? Thanks!
> 
> ```
> ERROR in ./node_modules/alphavantage/node_modules/dotenv/lib/main.js
> Module not found: Error: Can't resolve 'fs' in '/Users/XXXXX/Projects/myApp/myApp/node_modules/alphavantage/node_modules/dotenv/lib'
> ERROR in ./node_modules/request/lib/har.js
> Module not found: Error: Can't resolve 'fs' in '/Users/XXXXX/Projects/myApp/myApp/node_modules/request/lib'
> ```
> 
> ```
> /** plugins/alphavantage.js
>  * Init Alpha Vantage with your API key.
>  *
>  * @param {String} key
>  *   Your Alpha Vantage API key.
>  */
> import AlphaVantage from 'alphavantage'
> import Vue from 'vue'
> const alpha = AlphaVantage({
>   key: '0ZC3SK0K7V1R4UZZ'
> })
> 
> Vue.use(alpha)
> ```

were you able to find the solution?

**Comment by embeddedt** [comment]
I think this is meant for server-side usage, not client side, since it depends on the 'fs' module, which would not be available in a browser environment.

Plus, attempting to access AlphaVantage in a browser probably wouldn't work due to CORS issues.

**Comment by zackurben** [comment]
Sorry for the delay in replies.

As-is this is not exactly meant for web-app use. Your API key should be kept secret, because it's rate limited. The `dotenv` package is the issue here, it's pulling in the `fs` package to attempt environment variable resolution.

If you're using this for a local webapp to play around, you should be able to mock it via webpack or fork the repo can comment out the [problematic line](https://github.com/zackurben/alphavantage/blob/master/index.js#L3).

If this gets more feedback before I get more time, I'll look into adding official client side support. Additionally, any MRs are welcome to fix client side usage.

**Comment by zackurben** [comment]
I'm working on a solution for this now.

**Comment by zackurben** [comment]
Hi, this is now possible with the `2.0.0` release. If you do not have a bundler, you can crudely import the library into your page with the following: https://github.com/zackurben/alphavantage/blob/master/README.md#browser-usage

Otherwise, you can simply import the package! Let me know if you have any issues!
